<?php // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
header("Content-type:application/pdf");
$ch = curl_init();
$etab = $_POST['etab'];
$date = $_POST['date'];
$montant = $_POST['montant'];
$id = $_POST['id'];

curl_setopt($ch, CURLOPT_URL, 'https://invoice-generator.com');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"from\":\"TangoRythm\",\"to\":\"$etab\",\"logo\":\"https://www.zupimages.net/up/17/10/elu9.jpg\",\"number\":1,\"date\":\"$date\",\"items\":[{\"name\":\"Pack SMS\",\"quantity\":$id,\"unit_cost\":$montant}]}");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
echo $result;
curl_close ($ch);


?>